MT#59962 my_bool isn't supported anymore (mysql > 8.0.1)
From MySQL (mariadb) release notes:
"Incompatible Change: The my_bool type is no longer used in MySQL source code.
 Any third-party code that used this type to represent C boolean variables
 should use the bool or int C type instead.

 The change from my_bool to bool means that the mysql.h header file
 now requires a C++ or C99 compiler to compile. "

Fixes:

SW_Vsc.cpp: In member function ‘virtual void SW_VscDialog::onInvite(const AmSipRequest&)’:
SW_Vsc.cpp:913:5: error: ‘my_bool’ was not declared in this scope; did you mean ‘bool’?
  913 |     my_bool recon = 1;
      |     ^~~~~~~
      |     bool
SW_Vsc.cpp:981:57: error: ‘recon’ was not declared in this scope
  981 |     if (mysql_options(my_handler, MYSQL_OPT_RECONNECT, &recon) != 0)
      |                                                         ^~~~~
make: *** [../../core/plug-in/Makefile.app_module:83: SW_Vsc.o] Error 1

Change-Id: I74bc973299223fd00236569e905a57882b055f1a